# Generated by Django 4.0 on 2022-02-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('beat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_play_song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beat.songs')),
                ('last_play_song_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
