# Generated by Django 4.0 on 2022-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0008_remove_favourites_song_favourites_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='song',
        ),
        migrations.AddField(
            model_name='favourites',
            name='song',
            field=models.ManyToManyField(blank=True, to='beat.Songs'),
        ),
    ]
