# Generated by Django 4.0 on 2022-02-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0009_remove_favourites_song_favourites_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='song',
        ),
        migrations.AddField(
            model_name='favourites',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='beat.songs'),
            preserve_default=False,
        ),
    ]
