# Generated by Django 4.0 on 2022-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0012_alter_favourites_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='song',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='user',
        ),
        migrations.AddField(
            model_name='favourites',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_songs', to='beat.Songs'),
        ),
    ]
