# Generated by Django 4.0 on 2022-02-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('beat', '0013_remove_favourites_song_remove_favourites_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='favourites',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='beat.songs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
