# Generated by Django 4.0 on 2022-02-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0014_remove_favourites_favorited_by_favourites_song_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
