# Generated by Django 4.0 on 2022-02-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0017_favourites_delete_favouritessongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='song',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='user',
            field=models.CharField(max_length=500),
        ),
    ]
