# Generated by Django 4.0 on 2022-02-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0018_alter_favourites_song_alter_favourites_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='song',
            new_name='songs',
        ),
    ]
