# Generated by Django 4.0 on 2022-02-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beat', '0020_alter_favourites_songs_alter_favourites_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewReleases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Newsongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Newsongs', to='beat.songs')),
            ],
        ),
    ]
